LizardByte/libdisplaydevice

CMakeLists.txt, cmake/linux.cmake, cmake/macos.cmake, cmake/windows.cmake, tests/CMakeLists.txt
Fixes for platform specific builds (i.e. CodeQL for now)
=> build: fix platform specific builds

src/windows/include/displaydevice/windows/types.h, src/windows/include/displaydevice/windows/winapiutils.h, src/windows/winapiutils.cpp, tests/unit/windows/test_winapiutils.cpp
Add function for generating path for new topology
=> feat: add function for generating path for new topology

src/windows/include/displaydevice/windows/windisplaydevice.h, src/windows/include/displaydevice/windows/windisplaydeviceinterface.h, src/windows/windisplaydevicegeneral.cpp, tests/unit/windows/test_windisplaydevicegeneral.cpp
Add methods for getting API status and getting display name from ID.
=> feat: add methods for getting API status and getting display name from ID

src/common/include/displaydevice/types.h, src/windows/CMakeLists.txt, src/windows/include/displaydevice/windows/types.h, src/windows/include/displaydevice/windows/winapilayer.h, src/windows/include/displaydevice/windows/winapilayerinterface.h, src/windows/include/displaydevice/windows/windisplaydevice.h, src/windows/include/displaydevice/windows/windisplaydeviceinterface.h, src/windows/winapilayer.cpp, src/windows/windisplaydevicegeneral.cpp, tests/unit/windows/test_winapilayer.cpp, tests/unit/windows/test_windisplaydevicegeneral.cpp, tests/unit/windows/utils/comparison.cpp, tests/unit/windows/utils/comparison.h, tests/unit/windows/utils/mockwinapilayer.h
Add method for enumerating display devices + helper stuff...
Coverage will go down a little :/
=> feat: add method for enumerating display devices

CMakeLists.txt, cmake/Boost_DD.cmake, cmake/Json_DD.cmake, src/common/CMakeLists.txt, src/common/include/displaydevice/detail/jsonconverter.h, src/common/include/displaydevice/detail/jsonserializer.h, src/common/include/displaydevice/detail/jsonserializerdetails.h, src/common/include/displaydevice/json.h, src/common/json.cpp, src/common/jsonserializer.cpp, src/common/logging.cpp, src/windows/CMakeLists.txt, src/windows/include/displaydevice/windows/detail/jsonserializer.h, src/windows/include/displaydevice/windows/json.h, src/windows/json.cpp, src/windows/jsonserializer.cpp, tests/CMakeLists.txt, tests/fixtures/comparison.cpp, tests/fixtures/include/fixtures/comparison.h, tests/fixtures/include/fixtures/jsonconvertertest.h, tests/fixtures/testutils.cpp, tests/unit/general/CMakeLists.txt, tests/unit/general/test_json.cpp, tests/unit/general/test_jsonconverter.cpp, tests/unit/windows/test_jsonconverter.cpp
Added JSON serialization capabilities for custom types using the NLOHMAN JSON library.
The implementation details (library) are not exposed by design! As a side effect, people will have to
declare which types they want to use.
The main purpose of JSON is for logging mostly and in one case it will be used for persistence (future PR).
=> feat: Add JSON serialization capabilities

src/common/include/displaydevice/settingsmanagerinterface.h, src/windows/include/displaydevice/windows/settingsmanager.h, src/windows/include/displaydevice/windows/settingsutils.h, src/windows/settingsmanagerapply.cpp, src/windows/settingsmanagerrevert.cpp, src/windows/settingsutils.cpp, tests/unit/windows/test_settingsmanagerapply.cpp, tests/unit/windows/test_settingsmanagerrevert.cpp, tests/unit/windows/test_settingsutils.cpp, tests/unit/windows/utils/mockwindisplaydevice.cpp
Add primary device handling logic
=> feat: Add primary device handling logic

src/common/include/displaydevice/settingsmanagerinterface.h, src/windows/include/displaydevice/windows/settingsmanager.h, src/windows/include/displaydevice/windows/settingsutils.h, src/windows/settingsmanagerapply.cpp, src/windows/settingsutils.cpp, tests/unit/windows/test_settingsmanagerapply.cpp, tests/unit/windows/test_settingsutils.cpp
Add HDR state handling logic. HDR bug workaround will be added in a separate PR later.
=> feat: Add HDR state handling logic

src/common/filesettingspersistence.cpp, src/common/include/displaydevice/filesettingspersistence.h, src/common/include/displaydevice/settingspersistenceinterface.h, tests/unit/general/test_filesettingspersistence.cpp
Add file-based persistence handler
=> feat: Add file-based persistence handler

src/windows/include/display_device/windows/settings_utils.h, src/windows/settings_manager_revert.cpp, src/windows/settings_utils.cpp, tests/unit/windows/test_settings_manager_revert.cpp, tests/unit/windows/test_settings_utils.cpp
Perform more gradual topology restoration in case not all devices are enabled.
=> feat: Perform more gradual topology restoration

src/windows/win_display_device_general.cpp, tests/unit/windows/test_win_display_device_general.cpp
Make device enumeration more resilient in case for whatever magical reason the source mode is unavailable. This way we would still print the device ids that can be used for mapping device id -> display name in Sunshine.
=> feat: Make device enumeration more resilient

.github/workflows/ci.yml
Create a release and upload test binaries as artifacts.
=> ci: create release on push events

LICENSE
=> feat: use AGPLv3 license

README.md
Add interactive TOC per https://github.com/jothepro/doxygen-awesome-css/issues/157
=> docs: add interactive table of contents

cmake/Boost_DD.cmake
Do not create alias for existing targets
=> fix(boost): do not create alias for existing targets

.github/workflows/ci.yml, CMakeLists.txt
Fixes gcovr report generation.
=> ci(coverage): fix gcovr report generation

README.md
=> docs: update support url

src/windows/win_api_layer.cpp
Use new HDR WinAPI for W11 24H2 and above
=> fix(hdr): use new HDR WinAPI for W11 24H2 and above

src/common/types.cpp
Add workaround for older compilers
=> fix(types): add workaround for older compilers

src/common/types.cpp
improve comp. with old compilers
=> fix(types): improve comp. with old compilers

.github/workflows/ci.yml
Doxygen 1.14 has been released and should resolve issues with docs. See https://github.com/LizardByte/tray/pull/43
=> ci: re-enable docs
