LizardByte/libdisplaydevice

- .clang-format
- .flake8
- .github/workflows/ci.yml
- .github/workflows/cpp-lint.yml
- .github/workflows/python-flake8.yml
- .gitignore
- .gitmodules
- CMakeLists.txt
- LICENSE
- README.md
- README.rst
- cmake/windows.cmake
- codecov.yml
- scripts/requirements.txt
- scripts/update_clang_format.py
- src/main.cpp
- tests/CMakeLists.txt
- tests/conftest.cpp
- tests/unit/test_sample.cpp
- tests/utils.cpp
- tests/utils.h
See: https://github.com/LizardByte/Sunshine/pull/2032
> feat: initial framework setup

- .github/workflows/ci.yml
- codecov.yml
Some fixes as discovered in https://github.com/LizardByte/tray/pull/13
> ci: fix coverage exclusion

- CMakeLists.txt
- tests/CMakeLists.txt
Fix small typo in `tests/CMakeLists.txt`. Doesn't make any difference right now as `DD_SOURCES` is not yet populated in the main `CMakeLists.txt`
> fix: correct cmake typo

- tests/CMakeLists.txt
- tests/unit/platf/linux/test_linux_sample.cpp
- tests/unit/platf/macos/test_macos_sample.cpp
- tests/unit/platf/windows/test_windows_sample.cpp
Allow platform specific test code, other than the platform specific fixtures.
> tests: allow platform specific unit test files

- .codeql-prebuild-cpp-Linux.sh
- .codeql-prebuild-cpp-macOS.sh
- src/logging.cpp
Remove the usage of `std::format` to reduce GCC to V11.
> fix: downgrade to gcc 11

- .github/workflows/ci.yml
Skip coverage upload if not in LizardByte org, allowing contributors to run CI in their own fork more easily.
> ci: skip coverage upload if not in LizardByte org

- .codeql-prebuild-cpp-macOS.sh
macOS-14 runner is arm64 and therefore homebrew installs packages to a different location.
> build(codeql): fix gcc path for macOS

- .codeql-prebuild-cpp-Linux.sh
- .codeql-prebuild-cpp-Windows.sh
- .codeql-prebuild-cpp-macOS.sh
- .github/workflows/ci.yml
> build: use strategy matrix

- .gitmodules
- CMakeLists.txt
- cmake/Boost_DD.cmake
- src/windows/CMakeLists.txt
- src/windows/include/displaydevice/windows/winapilayer.h
- src/windows/include/displaydevice/windows/winapilayerinterface.h
- src/windows/winapilayer.cpp
- tests/unit/windows/test_winapilayer.cpp
> feat: add more methods to WinApiLayer

- .github/workflows/ci.yml
- CMakeLists.txt
- codecov.yml
- tests/CMakeLists.txt
Fix coverage reports after #17 inadvertently re-ordered some things related to coverage.
> ci: fix code coverage

- .github/workflows/ci.yml
Adds 3 exclusions for the gcovr report generation.
> ci(coverage): add gcovr exclusions

- .github/workflows/ci.yml
Attempt to improve re-running failed coverage uploads, by not having to re-build/test the whole project.
> ci: upload coverage in separate job matrix

- .github/workflows/ci.yml
When the coverage path is `build` codecov includes the build directory as part of the coverage results.
> ci: fix coverage artifact path

- .github/workflows/ci.yml
Coverage may not be accurate without checking out the branch.
> ci: checkout branch during coverage upload

- .github/workflows/ci.yml
- README.rst
Migrate CI (win) to UCRT64 and use debug build for coverage
> feat: migrate CI (win) to UCRT64 and use debug build for coverage

- cmake/Boost_DD.cmake
- tests/fixtures/fixtures.cpp
- tests/fixtures/fixtures.h
- tests/fixtures/testutils.cpp
- tests/fixtures/testutils.h
- tests/unit/windows/test_windisplaydevicetopology.cpp
It's annoying to have the screen blinking, so I made these kind of test skippable.
> feat: make system tests skipable via env

- src/common/include/displaydevice/types.h
- src/windows/include/displaydevice/windows/types.h
- src/windows/include/displaydevice/windows/winapiutils.h
- src/windows/winapiutils.cpp
- src/windows/windisplaydevicetopology.cpp
- tests/unit/windows/test_winapiutils.cpp
- tests/unit/windows/utils/mockwinapilayer.cpp
Ported more utils before moving to the display mode stuff.
> feat: port more win utils

- src/common/logging.cpp
> fix: refactor std::localtime out

- src/windows/include/displaydevice/windows/types.h
- src/windows/include/displaydevice/windows/windisplaydevice.h
- src/windows/include/displaydevice/windows/windisplaydeviceinterface.h
- src/windows/windisplaydevicemodes.cpp
- src/windows/windisplaydevicetopology.cpp
- tests/unit/windows/test_winapiutils.cpp
- tests/unit/windows/test_windisplaydevicemodes.cpp
- tests/unit/windows/test_windisplaydevicetopology.cpp
- tests/unit/windows/utils/comparison.cpp
- tests/unit/windows/utils/comparison.h
- tests/unit/windows/utils/guards.h
- tests/unit/windows/utils/helpers.cpp
- tests/unit/windows/utils/helpers.h
- tests/unit/windows/utils/mockwinapilayer.cpp
Added new API for display modes. Additionally, made some changes to the topology API to use a better recovery approach in case topology could not be set.
One test has been added to the skipped-list as we do not have enough displays with valid modes. The default CI display is bonkers and is not configurable (or at least I cannot guess valid display modes).
The "live" tests assume that the required display modes will be available as it's incredibly hard to enumerate them without involving another set of APIs, like DXGI...
[Allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-request …
> feat: Implement API for changing display modes

- src/common/include/displaydevice/types.h
- src/windows/include/displaydevice/windows/types.h
- src/windows/include/displaydevice/windows/winapilayer.h
- src/windows/include/displaydevice/windows/winapilayerinterface.h
- src/windows/include/displaydevice/windows/windisplaydevice.h
- src/windows/include/displaydevice/windows/windisplaydeviceinterface.h
- src/windows/winapilayer.cpp
- src/windows/windisplaydevicehdr.cpp
- tests/unit/windows/test_winapilayer.cpp
- tests/unit/windows/test_windisplaydevicehdr.cpp
- tests/unit/windows/utils/guards.h
- tests/unit/windows/utils/mockwinapilayer.h
Add methods for handling HDR state.
I predict that sadly the coverage might go down a little :/...
> feat: add methods for handling hdr state

- cmake/Boost_DD.cmake
> fix: Boost is now properly found using find_package

- src/common/include/displaydevice/settingsmanagerinterface.h
- src/windows/include/displaydevice/windows/settingsmanager.h
- src/windows/settingsmanagergeneral.cpp
- tests/unit/windows/test_settingsmanagergeneral.cpp
Add logic for resetting persistence
> feat: Add logic for resetting persistence

- src/windows/include/displaydevice/windows/settingsmanager.h
- src/windows/include/displaydevice/windows/settingsutils.h
- src/windows/settingsmanagerapply.cpp
- src/windows/settingsmanagerrevert.cpp
- src/windows/settingsutils.cpp
- tests/unit/windows/test_settingsmanagerapply.cpp
- tests/unit/windows/test_settingsmanagerrevert.cpp
- tests/unit/windows/test_settingsutils.cpp
Add workaround for HDR high-contrast color bug. This made reverting settings more complicated as I had to explicitly track the state whether we were going to modify any settings.
State tracking is required as the HDR blank thingy can make the actual monitors "blink", which is fine if actual changes are being done, but annoying if no changes were made and monitors are still "blinking" with every method call...
> feat: Add workaround for HDR high-contrast color bug

- src/common/include/displaydevice/retryscheduler.h
- src/common/retryscheduler.cpp
- tests/unit/general/test_retryscheduler.cpp
Added utility for... you guessed it! Retrying stuff until it succeeds! (to be used in Sunshine)
> feat: Implement RetryScheduler utility

- src/common/include/displaydevice/detail/jsonserializer.h
- src/common/include/displaydevice/detail/jsonserializerdetails.h
- src/common/include/displaydevice/types.h
- src/common/jsonserializer.cpp
- src/common/types.cpp
- src/windows/include/displaydevice/windows/detail/jsonserializer.h
- src/windows/include/displaydevice/windows/settingsutils.h
- src/windows/include/displaydevice/windows/types.h
- src/windows/include/displaydevice/windows/winapilayer.h
- src/windows/include/displaydevice/windows/winapilayerinterface.h
- src/windows/jsonserializer.cpp
- src/windows/settingsutils.cpp
- src/windows/types.cpp
- src/windows/winapilayer.cpp
- src/windows/windisplaydevicegeneral.cpp
- tests/fixtures/include/fixtures/jsonconvertertest.h
- tests/unit/general/test_comparison.cpp
- tests/unit/general/test_json.cpp
- tests/unit/general/test_jsonconverter.cpp
- tests/unit/windows/test_comparison.cpp
- tests/unit/windows/test_settingsutils.cpp
- tests/unit/windows/test_windisplaydevicegeneral.cpp
- tests/unit/windows/utils/mockwinapilayer.h
Use new FloatingPoint type to be more platform-compatible.
> feat: Use new FloatingPoint type

- tests/unit/general/test_retry_scheduler.cpp
Fix unstable RetryScheduler test case
> fix: Fix unstable RetryScheduler test case

- src/common/file_settings_persistence.cpp
- src/common/include/display_device/logging.h
- src/common/logging.cpp
- tests/unit/general/test_file_settings_persistence.cpp
- tests/unit/general/test_logging.cpp
Improve Sunshine compatibility by adding fatal log level and also improving compatibility with older compilers.
> feat: Improve Sunshine compatibility

- src/windows/include/display_device/windows/persistent_state.h
- src/windows/persistent_state.cpp
- tests/unit/windows/test_persistent_state.cpp
Simplify persistence load error handling. Incorrect `fallback` state could break the assumptions and we don't want that...
> feat: Simplify persistence load error handling

- src/windows/settings_manager_apply.cpp
> fix: add missing newlines in logs

- CMakeLists.txt
- src/windows/include/display_device/windows/types.h
- src/windows/settings_utils.cpp
Make library MSVC-compatible (so that it compiles :D).
> fix: make library MSVC-compatible

- src/common/include/display_device/detail/json_serializer_details.h
- src/common/include/display_device/json.h
- src/common/json.cpp
- src/windows/include/display_device/windows/detail/json_serializer.h
- src/windows/include/display_device/windows/json.h
- src/windows/include/display_device/windows/settings_manager.h
- src/windows/include/display_device/windows/settings_utils.h
- src/windows/include/display_device/windows/types.h
- src/windows/json.cpp
- src/windows/json_serializer.cpp
- src/windows/settings_manager_apply.cpp
- src/windows/settings_manager_general.cpp
- src/windows/settings_manager_revert.cpp
- src/windows/settings_utils.cpp
- src/windows/types.cpp
- tests/unit/general/test_json.cpp
- tests/unit/general/test_json_converter.cpp
- tests/unit/windows/test_json_converter.cpp
- tests/unit/windows/test_settings_manager_apply.cpp
- tests/unit/windows/test_settings_manager_general.cpp
- tests/unit/windows/test_settings_manager_revert.cpp
- tests/unit/windows/test_settings_utils.cpp
- tests/unit/windows/test_win_playground.cpp
Externalize workarounds for Windows.
Currently the HDR workaround for VDD is always applied (for toggling on/off HDR display states), even when VDD is not used and the workaround is probably not needed.
We should allow users to toggle such workarounds as they wish.
> feat: externalize workarounds for Windows

- CMakeLists.txt
Do not build docs for external projects. Sunshine and libdd are fighting over target names otherwise.
> fix: do not build docs for external projects

- src/common/include/display_device/retry_scheduler.h
- tests/unit/general/test_retry_scheduler.cpp
Added more options for scheduling the executor function.
It is a breaking change in a sense that function call has to be adapted, so I dunno if it still counts...
> feat(RetryScheduler): add more options for scheduling executor

- src/common/include/display_device/retry_scheduler.h
- tests/unit/general/test_retry_scheduler.cpp
Adds a const variant of RetryScheduler::execute...
> feat: add const version of RetryScheduler::execute

- src/common/include/display_device/retry_scheduler.h
- tests/unit/general/test_retry_scheduler.cpp
This fixes the broken auto deduction for lambdas introduced by https://github.com/LizardByte/libdisplaydevice/pull/119 and also makes the stop token no longer copyable (it still worked out of pure luck before...).
> fix: execute auto deduction and copyable stop token

- src/windows/include/display_device/windows/settings_manager.h
- src/windows/settings_manager_revert.cpp
- tests/unit/windows/test_settings_manager_revert.cpp
If the user manually switches back to the initial display topology and then reverts the settings, we would switch to the modified topology to undo stuff, but then never switch back to the initial topology matched the current one.
We are now smart enough to actually go "hmm, if current_topology == initial_topology, but then I switch to modified_topology, then current_topology != initial_topology after that! Me thinks thou should switch back'o to the ini_topo!" (yes, I'm losing sanity here)...
> fix: topology not always reverted back after reverting settings

- tests/unit/general/test_retry_scheduler.cpp
Lowered the lower bound by 1% for tests that are verifying that the thread has woken up within the expected time frame. They ideally should wake up on the lower bound delay, but sometime they wake up a little earlier.
> fix: unstable timed thread tests

- .github/workflows/ci.yml
- src/common/include/display_device/settings_manager_interface.h
- src/windows/include/display_device/windows/settings_manager.h
- src/windows/include/display_device/windows/settings_utils.h
- src/windows/settings_manager_apply.cpp
- src/windows/settings_manager_general.cpp
- src/windows/settings_manager_revert.cpp
- src/windows/settings_utils.cpp
- src/windows/win_api_layer.cpp
- tests/unit/windows/test_settings_manager_revert.cpp
- tests/unit/windows/test_settings_utils.cpp
Use full extended topology as a fallback. This increases the chances of use actually having a proper display!
> feat(settings_revert): use full extended topology as a fallback

- src/common/include/display_device/settings_manager_interface.h
- src/windows/include/display_device/windows/win_display_device_interface.h
- src/windows/settings_manager_general.cpp
- src/windows/win_display_device_general.cpp
- tests/unit/windows/test_settings_manager_general.cpp
- tests/unit/windows/test_win_display_device_general.cpp
Use better API availability test and also do not try to revert settings anymore in reset - keep it separate.
> fix(settings): better API test and clean persistence reset

- src/common/types.cpp
- src/windows/win_api_layer.cpp
fix compat. issues with older compilers
> fix(types): fix compat. issues with older compilers
